import type { Metadata } from "next";
import { Roboto,  } from "next/font/google";
import "./globals.css";

const manrope = Roboto({
  subsets: ["latin"],
  variable: "--font-manrope", // optional CSS variable for Tailwind/custom use
  weight: ["400", "500", "600", "700"], // choose weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
